@echo off && call %PATH_MODULES_COMMON%\init.bat %1 cmake

	REM ninja: error: build.ninja:288: multiple rules generate aom.lib [-w dupbuild=err]
cmake %CMAKE_OPTS% -G %CMAKE_TGT_VS% -A %archmsbuild% ^
-DCMAKE_INSTALL_PREFIX=%PATH_INSTALL% ^
-DCMAKE_BUILD_TYPE=%CMAKE_BUILD_TYPE% ^
-DBUILD_SHARED_LIBS=1 ^
-DENABLE_CCACHE=OFF ^
-DENABLE_DECODE_PERF_TESTS=OFF ^
-DENABLE_DISTCC=OFF ^
-DENABLE_DOCS=OFF ^
-DENABLE_ENCODE_PERF_TESTS=OFF ^
-DENABLE_EXAMPLES=OFF ^
-DENABLE_GOMA=OFF ^
-DENABLE_NASM=ON ^
-DENABLE_TESTDATA=OFF ^
-DENABLE_TESTS=OFF ^
-DENABLE_TOOLS=OFF ^
-DENABLE_WERROR=OFF ^
-DENABLE_NEON=OFF ^
-DENABLE_VSX=OFF ^
-DENABLE_MMX=ON ^
-DENABLE_SSE=ON ^
-DENABLE_SSE2=ON ^
-DENABLE_SSE3=ON ^
-DENABLE_SSSE3=ON ^
-DENABLE_SSE4_1=ON ^
-DENABLE_SSE4_2=%SSE42AVX% ^
-DENABLE_AVX=%SSE42AVX% ^
-DENABLE_AVX2=OFF ^
%PATH_SRC%\%1

%PATH_BIN_CYGWIN%\bash %PATH_MODULES_COMMON%/vcxproj.sh "%PATH_BUILD:\=/%/%1/" %AVXVCX% %PTFTS% %WKITVER% %VCTOOLSVER% %DOTNETVER%
MSBuild.exe %PATH_BUILD%\%1\%VCDIR%\AOM.sln %MSBUILD_OPTS% ^
/t:aom ^
/p:Configuration=%CMAKE_BUILD_TYPE% ^
/p:Platform="%archmsbuild%"

xcopy /C /F /Y %PATH_BUILD%\%1\%CMAKE_BUILD_TYPE%\aom.lib %PATH_INSTALL%\lib\*
for %%X in (pdb dll) do (xcopy /C /F /Y  %PATH_BUILD%\%1\%CMAKE_BUILD_TYPE%\aom.%%X %PATH_INSTALL%\bin\*)
if not exist %PATH_INSTALL%\include\aom\. mkdir %PATH_INSTALL%\include\aom
xcopy /C /F /Y  %PATH_SRC%\%1\aom\*.h %PATH_INSTALL%\include\aom\*
call do_php %PATH_UTILS%\sub\version.php %1 %PATH_INSTALL%\bin\aom.dll