@echo off && call %PATH_MODULES_COMMON%\init.bat %1 cmake

cmake %CMAKE_OPTS% -G %CMAKE_TGT_NINJA% ^
-DCMAKE_INSTALL_PREFIX=%PATH_INSTALL% ^
-DCMAKE_BUILD_TYPE=%CMAKE_BUILD_TYPE% ^
-DBUILD_SHARED_LIBS=ON ^
-DENABLE_CCACHE=OFF ^
-DENABLE_DECODE_PERF_TESTS=OFF ^
-DENABLE_DISTCC=OFF ^
-DENABLE_DOCS=OFF ^
-DENABLE_ENCODE_PERF_TESTS=OFF ^
-DENABLE_EXAMPLES=OFF ^
-DENABLE_GOMA=OFF ^
-DENABLE_NASM=ON ^
-DENABLE_TESTDATA=OFF ^
-DENABLE_TESTS=OFF ^
-DENABLE_TOOLS=OFF ^
-DENABLE_WERROR=OFF ^
-DENABLE_NEON=OFF ^
-DENABLE_VSX=OFF ^
-DENABLE_MMX=ON ^
-DENABLE_SSE=ON ^
-DENABLE_SSE2=ON ^
-DENABLE_SSE3=ON ^
-DENABLE_SSSE3=ON ^
-DENABLE_SSE4_1=ON ^
-DENABLE_SSE4_2=%SSE42AVX% ^
-DENABLE_AVX=%SSE42AVX% ^
-DENABLE_AVX2=OFF ^
%PATH_SRC%\%1

%PATH_BIN_CYGWIN%\bash %CYGPATH_MODULES_COMMON%/ninja.sh "%AVX%" "%CYGPATH_BUILD%/%1" "%NUMBER_OF_PROCESSORS%"
%NINJA% install

xcopy /C /F /Y  %PATH_BUILD%\%1\aom.pdb %PATH_INSTALL%\bin\*
move /Y %PATH_INSTALL%\lib\*_static.* %PATH_INSTALL%\%DIR_LIB_UNUSED%
call do_php %PATH_UTILS%\sub\version.php %1 %PATH_INSTALL%\bin\aom.dll