@echo off && call %PATH_MODULES_COMMON%\init.bat %1 cmake

cmake %CMAKE_OPTS% -G %CMAKE_TGT_NINJA% ^
-DCMAKE_INSTALL_PREFIX=%PATH_INSTALL% ^
-DBUILD_SHARED_LIBS=ON ^
-DENABLE_CCACHE=OFF ^
-DENABLE_DECODE_PERF_TESTS=OFF ^
-DENABLE_DISTCC=OFF ^
-DENABLE_DOCS=OFF ^
-DENABLE_ENCODE_PERF_TESTS=OFF ^
-DENABLE_EXAMPLES=OFF ^
-DENABLE_GOMA=OFF ^
-DENABLE_NASM=ON ^
-DENABLE_TESTDATA=OFF ^
-DENABLE_TESTS=OFF ^
-DENABLE_IDE_TEST_HOSTING=OFF ^
-DENABLE_TOOLS=OFF ^
-DENABLE_WERROR=OFF ^
-DENABLE_NEON=OFF ^
-DENABLE_NEON_DOTPROD=OFF ^
-DENABLE_NEON_I8MM=OFF ^
-DENABLE_VSX=OFF ^
-DENABLE_ARM_CRC32=OFF ^
-DENABLE_SVE=OFF ^
-DENABLE_SVE2=OFF ^
-DENABLE_MMX=ON ^
-DENABLE_SSE=ON ^
-DENABLE_SSE2=ON ^
-DENABLE_SSE3=ON ^
-DENABLE_SSSE3=ON ^
-DENABLE_SSE4_1=ON ^
-DENABLE_SSE4_2=%AVX_ON% ^
-DENABLE_AVX=%AVX_ON% ^
-DENABLE_AVX2=%AVX2_ON% ^
%PATH_SRC%\%1

%PATH_BIN_CYGWIN%\bash %CYGPATH_MODULES_COMMON%/ninja.sh "%AVX%" "%CYGPATH_BUILD%/%1" "%NUMBER_OF_PROCESSORS%"
	REM >= 3.10 : FAILED: aom_av1_rc.dll aom_av1_rc.lib on link
sed -i 's/\/GL //g' %CYGPATH_BUILD%/%1/build.ninja

%NINJA% install

xcopy /C /F /Y  %PATH_BUILD%\%1\aom.pdb %PATH_INSTALL%\bin\*
del /Q /F %PATH_INSTALL%\lib\aom_static.lib
call do_php %PATH_UTILS%\sub\version.php %1 %PATH_INSTALL%\bin\aom.dll