@echo off && call %PATH_MODULES_COMMON%\init.bat %1 cmake nocxx

REM -DAPR_INSTALL_PRIVATE_H=OFF mandaory
cmake %CMAKE_OPTS% -G %CMAKE_TGT_NINJA% ^
-DCMAKE_INSTALL_PREFIX=%PATH_INSTALL% ^
-DCMAKE_BUILD_TYPE=%CMAKE_BUILD_TYPE% ^
-DAPR_BUILD_TESTAPR=OFF ^
-DAPR_HAVE_IPV6=ON ^
-DAPR_INSTALL_PRIVATE_H=OFF ^
-DAPR_MINIMAL_BUILD=OFF ^
-DAPR_MODULAR_DSO=ON ^
-DAPR_POOL_DEBUG=OFF ^
-DAPR_XML_BACKEND=libxml2 ^
-DAPU_HAVE_CRYPTO=ON ^
-DAPU_HAVE_ICONV=ON ^
-DAPU_HAVE_ODBC=ON ^
-DAPU_HAVE_PGSQL=OFF ^
-DAPU_HAVE_SQLITE3=ON ^
-DBUILD_SHARED_LIBS=ON ^
-DINSTALL_PDB=ON ^
-DOPENSSL_ROOT_DIR=%PATH_INSTALL_OSSL% ^
-DOPENSSL_INCLUDE_DIR=%PATH_INSTALL_OSSL%/include ^
-DCMAKE_MODULE_PATH=C:/sdk/src/apr2/cmake/ ^
-DAPU_HAVE_MYSQL=ON ^
-DMySQL_LIBRARY=%PATH_MYSQL%/lib/mysqlclient.lib ^
-DMySQL_INCLUDE_DIR=%PATH_MYSQL%/include ^
%PATH_SRC%\%1

%PATH_BIN_CYGWIN%\bash %CYGPATH_MODULES_COMMON%/ninja.sh "%AVX%" "%CYGPATH_BUILD%/%1" "%NUMBER_OF_PROCESSORS%"
%NINJA% install

call do_php %PATH_UTILS%\sub\version.php apr2 %PATH_INSTALL%\bin\libapr-2.dll

REM apr-2 aprapp-2 
for %%D in (libaprapp-2) do (
	move /Y %PATH_INSTALL%\lib\%%D.lib %PATH_INSTALL%\%DIR_LIB_UNUSED%
	move /Y %PATH_BUILD%\%1\CMakeFiles\%%D.dir\%%D.pdb %PATH_INSTALL%\%DIR_LIB_UNUSED%
)