@echo off && call %PATH_MODULES_COMMON%\init.bat %1 cmake nocxx

cd /D %PATH_SRC%\%1
call buildconf.bat

cd /D %PATH_BUILD%\%1
if "%ARG_CMOPTS%"=="1" (@echo on)
cmake %CMAKE_OPTS% -G %CMAKE_TGT_NINJA% ^
-DCMAKE_INSTALL_PREFIX=%PATH_INSTALL% ^
-DCARES_STATIC=OFF ^
-DCARES_SHARED=ON ^
-DCARES_INSTALL=ON ^
-DCARES_BUILD_TESTS=OFF ^
-DCARES_BUILD_CONTAINER_TESTS=OFF ^
-DCARES_BUILD_TOOLS=OFF ^
-DCARES_MSVC_STATIC_RUNTIME=OFF ^
-DCARES_RANDOM_FILE=^%TEMP^% ^
-DCARES_SYMBOL_HIDING=OFF ^
-DCARES_THREADS=ON ^
-DCARES_COVERAGE=OFF ^
-DCARES_STATIC_PIC=OFF ^
-DCPACK_BINARY_7Z=OFF ^
-DCPACK_BINARY_IFW=OFF ^
-DCPACK_BINARY_INNOSETUP=OFF ^
-DCPACK_BINARY_NSIS=OFF ^
-DCPACK_BINARY_NUGET=OFF ^
-DCPACK_BINARY_WIX=OFF ^
-DCPACK_BINARY_ZIP=OFF ^
-DCPACK_SOURCE_7Z=OFF ^
-DCPACK_SOURCE_ZIP=OFF ^
%PATH_SRC%\%1
@echo off
if "%ARG_CMOPTS%"=="1" (exit /B)

%PATH_BIN_CYGWIN%\bash %CYGPATH_MODULES_COMMON%/ninja.sh "%AVX%" "%CYGPATH_BUILD%/%1" "%NUMBER_OF_PROCESSORS%"
%NINJA% install

xcopy /C /F /Y %PATH_BUILD%\%1\bin\cares.pdb %PATH_INSTALL%\bin\*
call do_php %PATH_UTILS%\sub\version.php %1 %PATH_INSTALL%\bin\cares.dll