@echo off && call %PATH_MODULES_COMMON%\init.bat %1 cmake nocxx

	REM set LIBCURL_TIMESTAMP
for /F "tokens=* USEBACKQ" %%F in (`%PATH_BIN_CYGWIN%\date -u`) do (set LIBCURL_TIMESTAMP=%%F)
sed -i 's/\[unreleased\]/%LIBCURL_TIMESTAMP%/g' %CYGPATH_SRC%/%1/include/curl/curlver.h

REM static build for mod_md with backend schannel only. 
	REM disabled: LIBSSH2 ARES OPENSSL CURL_EXE SHARED_LIBS BROTLI
		REM Protocols: -scp -sftp
		REM Features: -AsynchDNS -brotli -HTTP3 -TLS-SRP
	REM -- Protocols: dict file ftp ftps gopher gophers http https imap imaps ipfs ipns ldap ldaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp ws wss
	REM -- Features: alt-svc HSTS HTTP2 HTTPS-proxy HTTPSRR IDN IPv6 Kerberos Largefile libz NTLM SPNEGO SSL SSLS-EXPORT SSPI threadsafe Unicode UnixSockets zstd
	REM -- Enabled SSL backends: Schannel
cmake %CMAKE_OPTS% -G %CMAKE_TGT_NINJA% ^
-DCMAKE_UNITY_BUILD=1 ^
-DBUILD_CURL_EXE=OFF ^
-DBUILD_STATIC_CURL=OFF ^
-DBUILD_SHARED_LIBS=OFF ^
-DBUILD_STATIC_LIBS=ON ^
-DBUILD_TESTING=OFF ^
-DCURL_DISABLE_INSTALL=ON ^
-DBUILD_LIBCURL_DOCS=OFF ^
-DBUILD_MISC_DOCS=OFF ^
-DENABLE_CURL_MANUAL=OFF ^
-DPICKY_COMPILER=OFF ^
-DCURL_HIDDEN_SYMBOLS=ON ^
-DCURL_WERROR=OFF ^
-DCURL_ENABLE_EXPORT_TARGET=ON ^
-DCURL_STATIC_CRT=OFF ^
-DCURL_LTO=ON ^
-DCURL_ENABLE_SSL=ON ^
-DCURL_USE_GSSAPI=OFF ^
-DCURL_USE_LIBPSL=OFF ^
-DCURL_USE_LIBSSH=OFF ^
-DCURL_USE_MBEDTLS=OFF ^
-DCURL_USE_OPENSSL=OFF ^
-DCURL_USE_WOLFSSL=OFF ^
-DCURL_USE_GNUTLS=OFF ^
-DCURL_USE_SCHANNEL=ON ^
-DCURL_WINDOWS_SSPI=ON ^
-DHTTP_ONLY=OFF ^
-DCURL_DISABLE_OPENSSL_AUTO_LOAD_CONFIG=OFF ^
-DENABLE_CURLDEBUG=OFF ^
-DENABLE_DEBUG=OFF ^
-DENABLE_IPV6=ON ^
-DENABLE_UNIX_SOCKETS=ON ^
-DUSE_WIN32_IDN=ON ^
-DUSE_APPLE_IDN=OFF ^
-DUSE_APPLE_SECTRUST=OFF ^
-DUSE_WIN32_LDAP=ON ^
-DHAVE_LDAP_SSL=ON ^
-DENABLE_UNICODE=ON ^
-DUSE_LIBIDN2=OFF ^
-DUSE_LIBRTMP=OFF ^
-DUSE_HTTPSRR=ON ^
-DUSE_ECH=OFF ^
-DCURL_BROTLI=OFF ^
-DENABLE_ARES=OFF ^
-DENABLE_THREADED_RESOLVER=OFF ^
-DUSE_NGHTTP2=ON ^
-DCURL_USE_LIBSSH2=OFF ^
-DCURL_ZSTD=ON ^
-DBUILD_EXAMPLES=OFF ^
-DCURL_CA_SEARCH_SAFE=OFF ^
-DCURL_DISABLE_CA_SEARCH=OFF ^
-DCURL_TARGET_WINDOWS_VERSION=_WIN32_WINNT_WIN10 ^
-DCURL_USE_LIBUV=OFF ^
-DCURL_USE_PKGCONFIG=OFF ^
-DCURL_USE_RUSTLS=OFF ^
-DCURL_ZLIB=ON ^
-DLIBCURL_OUTPUT_NAME=%LIBCURL_STATIC_NAME% ^
-DCURL_CLANG_TIDY=OFF ^
-DCURL_CODE_COVERAGE=OFF ^
-DUSE_SSLS_EXPORT=ON ^
-D_CURL_PREFILL=ON ^
%PATH_SRC%\%1

%PATH_BIN_CYGWIN%\bash %CYGPATH_MODULES_COMMON%/ninja.sh "%AVX%" "%CYGPATH_BUILD%/%1" "%NUMBER_OF_PROCESSORS%"
sed -i -E 's/TARGET_COMPILE_PDB.*/TARGET_COMPILE_PDB = lib\\\\%LIBCURL_STATIC_NAME%\.pdb/g' %CYGPATH_BUILD%/%1/build.ninja
%NINJA% %LIBCURL_STATIC_NAME%.lib
for %%E in (lib pdb) do (xcopy /C /F /Y %PATH_BUILD%\%1\lib\%LIBCURL_STATIC_NAME%.%%E %PATH_INSTALL%\%DIR_LIB_STATIC%\*)

REM CURL_USE_SCHANNEL - MultiSSL cannot be enabled with HTTP/3 and vice versa
REM ENABLE_THREADED_RESOLVER must be OFF cf. https://github.com/curl/curl/issues/16379
REM	-- Protocols: dict file ftp ftps gopher gophers http https imap imaps ipfs ipns ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp ws wss
REM	-- Features: alt-svc AsynchDNS brotli HSTS HTTP2 HTTP3 HTTPS-proxy HTTPSRR IDN IPv6 Kerberos Largefile libz NTLM SPNEGO SSL SSLS-EXPORT SSPI threadsafe TLS-SRP Unicode UnixSockets zstd
REM	-- Enabled SSL backends: OpenSSL v3+
cmake %CMAKE_OPTS% -G %CMAKE_TGT_NINJA% ^
-DCMAKE_UNITY_BUILD=1 ^
-DCMAKE_INSTALL_PREFIX=%PATH_INSTALL% ^
-DIMPORT_LIB_SUFFIX= ^
-DBUILD_CURL_EXE=ON ^
-DBUILD_SHARED_LIBS=ON ^
-DBUILD_STATIC_LIBS=OFF ^
-DBUILD_STATIC_CURL=OFF ^
-DBUILD_TESTING=OFF ^
-DCURL_DISABLE_INSTALL=OFF ^
-DBUILD_LIBCURL_DOCS=OFF ^
-DBUILD_MISC_DOCS=OFF ^
-DENABLE_CURL_MANUAL=OFF ^
-DPICKY_COMPILER=OFF ^
-DCURL_HIDDEN_SYMBOLS=ON ^
-DCURL_WERROR=OFF ^
-DCURL_ENABLE_EXPORT_TARGET=ON ^
-DCURL_STATIC_CRT=OFF ^
-DCURL_LTO=ON ^
-DCURL_ENABLE_SSL=ON ^
-DCURL_USE_GSSAPI=OFF ^
-DCURL_USE_GSASL=OFF ^
-DCURL_USE_LIBBACKTRACE=OFF ^
-DCURL_USE_LIBPSL=OFF ^
-DCURL_USE_LIBSSH=OFF ^
-DCURL_USE_MBEDTLS=OFF ^
-DCURL_USE_OPENSSL=ON ^
-DCURL_USE_WOLFSSL=OFF ^
-DCURL_USE_GNUTLS=OFF ^
-DCURL_WINDOWS_SSPI=ON ^
-DHTTP_ONLY=OFF ^
-DCURL_DISABLE_OPENSSL_AUTO_LOAD_CONFIG=OFF ^
-DENABLE_CURLDEBUG=OFF ^
-DENABLE_DEBUG=OFF ^
-DENABLE_IPV6=ON ^
-DENABLE_UNIX_SOCKETS=ON ^
-DUSE_WIN32_IDN=ON ^
-DUSE_APPLE_IDN=OFF ^
-DUSE_APPLE_SECTRUST=OFF ^
-DUSE_WIN32_LDAP=ON ^
-DHAVE_LDAP_SSL=ON ^
-DENABLE_UNICODE=ON ^
-DUSE_LIBIDN2=OFF ^
-DUSE_LIBRTMP=OFF ^
-DUSE_HTTPSRR=ON ^
-DUSE_ECH=OFF ^
-DCURL_BROTLI=ON ^
-DENABLE_ARES=ON ^
	-DENABLE_THREADED_RESOLVER=OFF ^
-DUSE_NGHTTP2=ON ^
-DCURL_USE_LIBSSH2=ON ^
-DCURL_ZSTD=ON ^
-DBUILD_EXAMPLES=OFF ^
-DCURL_CA_SEARCH_SAFE=OFF ^
-DCURL_DISABLE_CA_SEARCH=OFF ^
-DCURL_LIBCURL_SOVERSION=OFF ^
-DCURL_LIBCURL_VERSIONED_SYMBOLS=OFF ^
-DCURL_TARGET_WINDOWS_VERSION=_WIN32_WINNT_WIN10 ^
-DCURL_USE_LIBUV=OFF ^
-DCURL_USE_PKGCONFIG=OFF ^
-DCURL_USE_RUSTLS=OFF ^
-DCURL_ZLIB=ON ^
-DLIBCURL_OUTPUT_NAME=libcurl ^
-DCURL_CLANG_TIDY=OFF ^
-DCURL_CODE_COVERAGE=OFF ^
-DUSE_SSLS_EXPORT=ON ^
-D_CURL_PREFILL=ON ^
-DCURL_USE_SCHANNEL=OFF ^
-DUSE_NGTCP2=ON ^
-DUSE_NGHTTP3=ON ^
-DUSE_QUICHE=OFF ^
%PATH_SRC%\%1

%PATH_BIN_CYGWIN%\bash %CYGPATH_MODULES_COMMON%/ninja.sh "%AVX%" "%CYGPATH_BUILD%/%1" "%NUMBER_OF_PROCESSORS%"
%NINJA% install

xcopy /C /F /Y %PATH_BUILD%\%1\lib\libcurl.pdb %PATH_INSTALL%\bin\*
xcopy /C /F /Y %PATH_BUILD%\%1\src\curl.pdb %PATH_INSTALL%\bin\*

for %%E in (libcurl.dll curl.exe) do (call do_php %PATH_UTILS%\sub\version.php %1 %PATH_INSTALL%\bin\%%E "%CURL_DESC%")

REM curl https://curl.se/ca/cacert.pem -o %PATH_INSTALL%\bin\curl-ca-bundle.crt
cd /D %PATH_INSTALL%\bin
call perl %PATH_SRC%\%1\scripts\mk-ca-bundle.pl curl-ca-bundle.crt
for %%E in (certdata.txt curl-config wcurl) do (rm -fv %PATH_INSTALL%\bin\%%E)
if %LOCAL_COPY% == 1 if %LOCAL_COPY_AVX_ECHO% == %AVXECHO%  if %LOCAL_COPY_MSVC_VER% == %MSVC_VER% (xcopy /C /F /Y %PATH_INSTALL%\bin\curl-ca-bundle.crt %LOCAL_PATH_CURLCA%\*)