set CURL_SSL_ENGINE=%2
if %CURL_SSL_ENGINE% == winssl (set CURL_SSLNMAKE=-DCMAKE_USE_OPENSSL=OFF -DCMAKE_USE_LIBSSH2=OFF -DCMAKE_USE_SCHANNEL=ON -DCURL_WINDOWS_SSPI=ON)
if %CURL_SSL_ENGINE% == openssl (set CURL_SSLNMAKE=-DCMAKE_USE_OPENSSL=ON -DCMAKE_USE_LIBSSH2=ON -DCMAKE_USE_WINSSL=OFF -DOPENSSL_ROOT_DIR=%PATH_INSTALL% -DOPENSSL_INCLUDE_DIR=%PATH_INSTALL%\include -DLIBSSH2_LIBRARY=%PATH_INSTALL%\lib\libssh2.lib -DLIBSSH2_INCLUDE_DIR=%PATH_INSTALL%\include  -DCURL_WINDOWS_SSPI=OFF)

echo %CURL_SSLNMAKE%

if exist %PATH_INSTALL%\%1\%CURL_SSL_ENGINE%\. rmdir /S /Q %PATH_INSTALL%\%1\%CURL_SSL_ENGINE%
mkdir %PATH_INSTALL%\%1\%CURL_SSL_ENGINE%
	REM set ssl engine as ProductName
for %%I in (lib/libcurl.rc src/curl.rc) do (sed -i -E 's/"ProductName",.*/"ProductName",      "ssl_version: %CURL_SSL_ENGINE%\\\\0"/g' %CYGPATH_SRC%/%1/%%I)

	REM unset options (default)
REM -DENABLE_DEBUG=OFF -DENABLE_CURLDEBUG=OFF -DCURL_STATIC_CRT=OFF -DENABLE_INET_PTON=ON -DHTTP_ONLY=OFF -DCURL_DISABLE_FTP=OFF -DCURL_DISABLE_LDAP=OFF -DCURL_DISABLE_TELNET=OFF -DCURL_DISABLE_DICT=OFF -DCURL_DISABLE_FILE=OFF -DCURL_DISABLE_TFTP=OFF -DCURL_DISABLE_HTTP=OFF -DCURL_DISABLE_LDAPS=OFF -DCURL_DISABLE_RTSP=OFF -DCURL_DISABLE_PROXY=OFF -DCURL_DISABLE_POP3=OFF -DCURL_DISABLE_IMAP=OFF -DCURL_DISABLE_SMTP=OFF -DCURL_DISABLE_GOPHER=OFF -DCURL_ENABLE_MQTT=OFF -DCURL_DISABLE_COOKIES=OFF -DCURL_DISABLE_CRYPTO_AUTH=OFF -DCURL_DISABLE_VERBOSE_STRINGS=OFF -DENABLE_IPV6=ON -DCMAKE_USE_SECTRANSP=OFF -DCMAKE_USE_MBEDTLS=OFF -DCMAKE_USE_BEARSSL=OFF -DCMAKE_USE_NSS=OFF -DCMAKE_USE_WOLFSSL=OFF -DCMAKE_USE_OPENLDAP=OFF -DCMAKE_USE_GSSAPI=OFF -DENABLE_UNIX_SOCKETS=OFF

cmake ^
	%CMAKE_OPTS% ^
	-DCMAKE_INSTALL_PREFIX=%PATH_INSTALL%\%1\%CURL_SSL_ENGINE% ^
	-DCMAKE_BUILD_TYPE=%CMAKE_BUILD_TYPE% ^
	-DCURL_WERROR=OFF ^
	-DBUILD_CURL_EXE=ON ^
	-DBUILD_SHARED_LIBS=ON ^
	-DCURL_LTO=ON ^
	-DENABLE_THREADED_RESOLVER=ON ^
	-DENABLE_MANUAL=OFF ^
	-DBUILD_TESTING=OFF ^
	-DUSE_WIN32_LDAP=ON ^
	-DCURL_ZLIB=ON ^
	-DZLIB_LIBRARY=%PATH_INSTALL%\lib\zlib.lib ^
	-DZLIB_INCLUDE_DIR=%PATH_INSTALL%\include ^
	-DCURL_BROTLI=ON ^
	-DBROTLIDEC_LIBRARY=%PATH_INSTALL%\lib\brotlidec.lib ^
	-DBROTLICOMMON_LIBRARY=%PATH_INSTALL%\lib\brotlicommon.lib ^
	-DBROTLI_INCLUDE_DIR=%PATH_INSTALL%\include ^
	-DENABLE_ARES=ON ^
	-DCARES_LIBRARY=%PATH_INSTALL%\lib\cares.lib ^
	-DCARES_INCLUDE_DIR=%PATH_INSTALL%\include ^
	-DUSE_NGHTTP2=ON ^
	-DNGHTTP2_LIBRARY=%PATH_INSTALL%\lib\nghttp2.lib ^
	-DNGHTTP2_INCLUDE_DIR=%PATH_INSTALL%\include ^
	%CURL_SSLNMAKE% ^
	%PATH_SRC%\%1

%PATH_BIN_CYGWIN%\bash %CYGPATH_MODULES_COMMON%/flags.sh "%AVXSED%" "%CYGPATH_BUILD%/%1" "%NUMBER_OF_PROCESSORS%"
nmake %NMAKE_OPTS% clean install

xcopy /C /F /Y %PATH_BUILD%\%1\lib\libcurl.pdb %PATH_INSTALL%\%1\%CURL_SSL_ENGINE%\bin\*
xcopy /C /F /Y %PATH_BUILD%\%1\src\curl.pdb %PATH_INSTALL%\%1\%CURL_SSL_ENGINE%\bin\*