@echo off && call %PATH_MODULES_COMMON%\init.bat %1 cmake nocxx

if "%ARG_CMOPTS%"=="1" (@echo on)
cmake %CMAKE_OPTS% -G %CMAKE_TGT_NINJA% ^
-DCMAKE_UNITY_BUILD=1 ^
-DCMAKE_INSTALL_PREFIX=%PATH_INSTALL% ^
-DBUILD_SHARED_LIBS=ON ^
-DFT_DISABLE_ZLIB=OFF ^
-DFT_DISABLE_BZIP2=OFF ^
-DFT_DISABLE_BROTLI=OFF ^
-DFT_DISABLE_HARFBUZZ=ON ^
-DFT_DISABLE_PNG=OFF ^
-DFT_ENABLE_ERROR_STRINGS=OFF ^
-DCPACK_SOURCE_7Z=OFF ^
-DCPACK_SOURCE_ZIP=OFF ^
-DFT_REQUIRE_BROTLI=ON ^
-DFT_REQUIRE_BZIP2=ON ^
-DFT_REQUIRE_PNG=ON ^
-DFT_REQUIRE_ZLIB=ON ^
%PATH_SRC%\%1
@echo off
if "%ARG_CMOPTS%"=="1" (exit /B)

%PATH_BIN_CYGWIN%\bash %CYGPATH_MODULES_COMMON%/ninja.sh "%AVX%" "%CYGPATH_BUILD%/%1" "%NUMBER_OF_PROCESSORS%"
%NINJA% install

xcopy /C /F /Y %PATH_BUILD%\%1\freetype.pdb %PATH_INSTALL%\bin\*
call do_php %PATH_UTILS%\sub\version.php %1 %PATH_INSTALL%\bin\freetype.dll