@echo off && call %PATH_MODULES_COMMON%\init.bat %1 cmake

sed -i -E "s/20189999/%SCM_COMORREV_DATE:-=%/g" %CYGPATH_SRC%/%1/cmake/modules/thirdparty/GetGitHeadDate.cmake

if exist %PATH_INSTALL%\_%1\. rmdir /S /Q %PATH_INSTALL%\_%1
mkdir %PATH_INSTALL%\_%1

REM -DGDAL_USE_JPEG12_INTERNAL=ON ^
REM -DGDAL_USE_QHULL_INTERNAL=ON ^
REM -DGDAL_USE_JSONC_INTERNAL=ON ^
REM -DGDAL_USE_OPENCAD_INTERNAL=ON ^
	REM !! disable internal
REM -DCMAKE_DISABLE_FIND_PACKAGE_JSONC=1 ^
	REM !! disable internal
REM -DCMAKE_DISABLE_FIND_PACKAGE_OpenCAD=1 ^
	REM https://gdal.org/development/building_from_source.html
if "%ARG_CMOPTS%"=="1" (@echo on)
cmake %CMAKE_OPTS% -G %CMAKE_TGT_NINJA% ^
-DCMAKE_UNITY_BUILD=1 ^
-DCMAKE_INSTALL_PREFIX=%PATH_INSTALL%\_%1 ^
-DGDAL_LIB_OUTPUT_NAME=libgdal ^
-DBUILD_APPS=ON ^
-DBUILD_CSHARP_BINDINGS=OFF ^
-DBUILD_DOCS=OFF ^
-DBUILD_JAVA_BINDINGS=OFF ^
-DBUILD_PYTHON_BINDINGS=OFF ^
-DBUILD_SHARED_LIBS=ON ^
-DBUILD_TESTING=OFF ^
-DCLANG_TIDY_ENABLED=OFF ^
-DCSHARP_MONO=OFF ^
-DUSE_CCACHE=OFF ^
-DUSE_ONLY_EMBEDDED_RESOURCE_FILES=OFF ^
-DUSE_PRECOMPILED_HEADERS=OFF ^
-DEMBED_RESOURCE_FILES=OFF ^
-DENABLE_GNM=ON ^
-DENABLE_IPO=ON ^
-DENABLE_PAM=ON ^
-DENABLE_DEFLATE64=ON ^
-DGDAL_BUILD_OPTIONAL_DRIVERS=ON ^
-DGDAL_AUTOLOAD_PLUGINS=ON ^
-DGDAL_ENABLE_ALGORITHMS=ON ^
-DGDAL_ENABLE_PLUGINS=ON ^
-DGDAL_FIND_PACKAGE_PROJ_MODE=MODULE ^
-DGDAL_OBJECT_LIBRARIES_POSITION_INDEPENDENT_CODE=ON ^
-DGDAL_SET_INSTALL_RELATIVE_RPATH=OFF ^
-DGDAL_VRT_ENABLE_RAWRASTERBAND=ON ^
-DOGR_BUILD_OPTIONAL_DRIVERS=ON ^
-DOGR_SQLITE_ALLOW_LOAD_EXTENSIONS=ON ^
-DGDAL_USE_EXTERNAL_LIBS=ON ^
-DGDAL_USE_INTERNAL_LIBS=WHEN_NO_EXTERNAL ^
-DGDAL_USE_AVIF=ON ^
-DGDAL_USE_CURL=ON ^
-DGDAL_USE_DEFLATE=ON ^
-DGDAL_USE_EXPAT=ON ^
-DGDAL_USE_GEOTIFF=ON ^
-DGDAL_USE_GEOS=ON ^
-DGDAL_USE_GIF=ON ^
-DGDAL_USE_HEIF=ON ^
-DGDAL_USE_ICONV=ON ^
	-DIconv_CHARSET_LIBRARY=%PATH_INSTALL%/lib/libiconv.lib ^
-DGDAL_USE_JPEG=ON ^
	-DEXPECTED_JPEG_LIB_VERSION=80 ^
-DGDAL_USE_LERC=ON ^
-DGDAL_USE_LIBLZMA=ON ^
-DGDAL_USE_LIBXML2=ON ^
-DGDAL_USE_MYSQL=ON ^
-DGDAL_USE_ODBC=ON ^
-DGDAL_USE_OPENSSL=ON ^
-DGDAL_USE_PCRE2=ON ^
-DGDAL_USE_PNG=ON ^
-DGDAL_USE_QHULL=ON ^
	-DQHULL_PACKAGE_NAME=qhull_r ^
-DGDAL_USE_SQLITE3=ON ^
-DGDAL_USE_TIFF=ON ^
-DGDAL_USE_WEBP=ON ^
-DGDAL_USE_ZLIB=ON ^
-DGDAL_USE_ZSTD=ON ^
-DGDAL_USE_JSONC_INTERNAL=ON ^
-DGDAL_USE_OPENCAD_INTERNAL=ON ^
-DCMAKE_DISABLE_FIND_PACKAGE_AdbcDriverManager=1 ^
-DCMAKE_DISABLE_FIND_PACKAGE_Armadillo=1 ^
-DCMAKE_DISABLE_FIND_PACKAGE_Arrow=1 ^
-DCMAKE_DISABLE_FIND_PACKAGE_basisu=1 ^
-DCMAKE_DISABLE_FIND_PACKAGE_Blosc=1 ^
-DCMAKE_DISABLE_FIND_PACKAGE_BRUNSLI=1 ^
-DCMAKE_DISABLE_FIND_PACKAGE_CryptoPP=1 ^
-DCMAKE_DISABLE_FIND_PACKAGE_CSharp=1 ^
-DCMAKE_DISABLE_FIND_PACKAGE_Doxygen=1 ^
-DCMAKE_DISABLE_FIND_PACKAGE_ECW=1 ^
-DCMAKE_DISABLE_FIND_PACKAGE_ExprTk=1 ^
-DCMAKE_DISABLE_FIND_PACKAGE_FileGDB=1 ^
-DCMAKE_DISABLE_FIND_PACKAGE_FreeXL=1 ^
-DCMAKE_DISABLE_FIND_PACKAGE_FYBA=1 ^
-DCMAKE_DISABLE_FIND_PACKAGE_HDF4=1 ^
-DCMAKE_DISABLE_FIND_PACKAGE_HDF5=1 ^
-DCMAKE_DISABLE_FIND_PACKAGE_HDFS=1 ^
-DCMAKE_DISABLE_FIND_PACKAGE_IDB=1 ^
-DCMAKE_DISABLE_FIND_PACKAGE_KDU=1 ^
-DCMAKE_DISABLE_FIND_PACKAGE_LibKML=1 ^
-DCMAKE_DISABLE_FIND_PACKAGE_libQB3=1 ^
-DCMAKE_DISABLE_FIND_PACKAGE_LZ4=1 ^
-DCMAKE_DISABLE_FIND_PACKAGE_MONGOCXX=1 ^
-DCMAKE_DISABLE_FIND_PACKAGE_MRSID=1 ^
-DCMAKE_DISABLE_FIND_PACKAGE_MSSQL_NCLI=1 ^
-DCMAKE_DISABLE_FIND_PACKAGE_MSSQL_ODBC=1 ^
-DCMAKE_DISABLE_FIND_PACKAGE_muparser=1 ^
-DCMAKE_DISABLE_FIND_PACKAGE_NetCDF=1 ^
-DCMAKE_DISABLE_FIND_PACKAGE_ODBCCPP=1 ^
-DCMAKE_DISABLE_FIND_PACKAGE_OpenDrive=1 ^
-DCMAKE_DISABLE_FIND_PACKAGE_OpenEXR=1 ^
-DCMAKE_DISABLE_FIND_PACKAGE_OpenJPEG=1 ^
-DCMAKE_DISABLE_FIND_PACKAGE_Oracle=1 ^
-DCMAKE_DISABLE_FIND_PACKAGE_Podofo=1 ^
-DCMAKE_DISABLE_FIND_PACKAGE_Poppler=1 ^
-DCMAKE_DISABLE_FIND_PACKAGE_PostgreSQL=1 ^
-DCMAKE_DISABLE_FIND_PACKAGE_Python=1 ^
-DCMAKE_DISABLE_FIND_PACKAGE_RASTERLITE2=1 ^
-DCMAKE_DISABLE_FIND_PACKAGE_SFCGAL=1 ^
-DCMAKE_DISABLE_FIND_PACKAGE_Shapelib=1 ^
-DCMAKE_DISABLE_FIND_PACKAGE_SPATIALITE=1 ^
-DCMAKE_DISABLE_FIND_PACKAGE_SWIG=1 ^
-DCMAKE_DISABLE_FIND_PACKAGE_TileDB=1 ^
-DCMAKE_DISABLE_FIND_PACKAGE_XercesC=1 ^
%PATH_SRC%\%1
@echo off
if "%ARG_CMOPTS%"=="1" (exit /B)

%PATH_BIN_CYGWIN%\bash %CYGPATH_MODULES_COMMON%/ninja.sh "%AVX%" "%CYGPATH_BUILD%/%1" "%NUMBER_OF_PROCESSORS%"
%NINJA% install

xcopy /C /F /Y %PATH_BUILD%\%1\libgdal.pdb %PATH_INSTALL%\_%1\bin\*
call do_php %PATH_UTILS%\sub\version.php %1 %PATH_INSTALL%\_%1\bin\libgdal.dll
for /f "tokens=*" %%G in ('dir %PATH_INSTALL%\_%1\bin\*.exe/b') do  (
	call do_php %PATH_UTILS%\sub\version.php %1 %PATH_INSTALL%\_%1\bin\%%G
	xcopy /C /F /Y %PATH_BUILD%\%1\apps\%%~nG.pdb %PATH_INSTALL%\_%1\bin\*
)
move /Y %PATH_INSTALL%\_%1\lib\gdalplugins %PATH_INSTALL%\_%1\bin\gdalplugins
for /f "tokens=*" %%G in ('dir %PATH_INSTALL%\_%1\bin\gdalplugins\*.dll /b') do  (
	call do_php %PATH_UTILS%\sub\version.php %1 %PATH_INSTALL%\_%1\bin\gdalplugins\%%G
	xcopy /C /F /Y %PATH_BUILD%\%1\gdalplugins\%%~nG.pdb %PATH_INSTALL%\_%1\bin\gdalplugins\*
)