call %PATH_HTTPD_SDK%\build.bat zlib
call %PATH_HTTPD_SDK%\build.bat openssl
call %PATH_HTTPD_SDK%\build.bat jemalloc
call %PATH_HTTPD_SDK%\build.bat brotli
call %PATH_HTTPD_SDK%\build.bat jansson
call %PATH_HTTPD_SDK%\build.bat bzip2
call %PATH_HTTPD_SDK%\build.bat libiconv
call %PATH_HTTPD_SDK%\build.bat libxml2
call %PATH_HTTPD_SDK%\build.bat pcre
call %PATH_HTTPD_SDK%\build.bat libevent
call %PATH_HTTPD_SDK%\build.bat libev
call %PATH_HTTPD_SDK%\build.bat c-ares
call %PATH_HTTPD_SDK%\build.bat nghttp2
call %PATH_HTTPD_SDK%\build.bat libssh2
call %PATH_HTTPD_SDK%\build.bat curl
call %PATH_HTTPD_SDK%\build.bat libexpat
call %PATH_HTTPD_SDK%\build.bat libmaxminddb
call %PATH_HTTPD_SDK%\build.bat sqlite
exit /B
call %PATH_HTTPD_SDK%\build.bat apr
call %PATH_HTTPD_SDK%\build.bat lua
call %PATH_HTTPD_SDK%\build.bat httpd
call %PATH_HTTPD_SDK%\build.bat mod_h264_streaming