call %PATH_BATCH%\build.bat clean NOLOG
call %PATH_BATCH%\build.bat brotli NOLOG
call %PATH_BATCH%\build.bat jansson NOLOG
call %PATH_BATCH%\build.bat bzip2 NOLOG
call %PATH_BATCH%\build.bat zlib NOLOG
call %PATH_BATCH%\build.bat openssl NOLOG
call %PATH_BATCH%\build.bat jemalloc NOLOG
call %PATH_BATCH%\build.bat libiconv NOLOG
call %PATH_BATCH%\build.bat libxml2 NOLOG
call %PATH_BATCH%\build.bat pcre NOLOG
call %PATH_BATCH%\build.bat libevent NOLOG
call %PATH_BATCH%\build.bat libev NOLOG
call %PATH_BATCH%\build.bat cares NOLOG
call %PATH_BATCH%\build.bat nghttp2 NOLOG
call %PATH_BATCH%\build.bat libssh2 NOLOG
call %PATH_BATCH%\build.bat curl NOLOG
call %PATH_BATCH%\build.bat libexpat NOLOG
call %PATH_BATCH%\build.bat libmaxminddb NOLOG
call %PATH_BATCH%\build.bat sqlite NOLOG
call %PATH_BATCH%\build.bat apr NOLOG
call %PATH_BATCH%\build.bat lua NOLOG
call %PATH_BATCH%\build.bat httpd NOLOG