@echo off && call %PATH_MODULES_COMMON%\init.bat %1 cmake nocxx

if "%ARG_CMOPTS%"=="1" (@echo on)
cmake %CMAKE_OPTS% -G %CMAKE_TGT_NINJA% ^
-DCMAKE_POLICY_VERSION_MINIMUM=3.5 ^
-DCMAKE_INSTALL_PREFIX=%PATH_INSTALL% ^
-DUSE_URANDOM=OFF ^
-DJANSSON_EXAMPLES=OFF ^
-DJANSSON_BUILD_DOCS=OFF ^
-DJANSSON_BUILD_SHARED_LIBS=ON ^
-DUSE_DTOA=ON ^
-DJANSSON_INSTALL=ON ^
-DJANSSON_LIBRARIES=jansson ^
-DJANSSON_STATIC_CRT=OFF ^
-DJANSSON_WITHOUT_TESTS=ON ^
-DUSE_WINDOWS_CRYPTOAPI=ON ^
%PATH_SRC%\%1
@echo off
if "%ARG_CMOPTS%"=="1" (exit /B)

%PATH_BIN_CYGWIN%\bash %CYGPATH_MODULES_COMMON%/ninja.sh "%AVX%" "%CYGPATH_BUILD%/%1" "%NUMBER_OF_PROCESSORS%"
%NINJA% install

xcopy /C /F /Y %PATH_BUILD%\%1\bin\jansson.pdb %PATH_INSTALL%\bin\*
call do_php %PATH_UTILS%\sub\version.php %1 %PATH_INSTALL%\bin\jansson.dll