@echo off && call %PATH_MODULES_COMMON%\init.bat %1 cmake nocxx

REM AVIF_CODEC_AOM - requires CMake, NASM
REM AVIF_CODEC_DAV1D - requires Meson, Ninja, NASM
REM AVIF_CODEC_LIBGAV1 - requires CMake, Ninja
REM AVIF_CODEC_RAV1E - requires cargo (Rust), NASM

cmake %CMAKE_OPTS% -G %CMAKE_TGT_NINJA% ^
-DCMAKE_DISABLE_FIND_PACKAGE_PkgConfig=ON ^
-DCMAKE_INSTALL_PREFIX=%PATH_INSTALL% ^
-DAVIF_CODEC_AOM=SYSTEM ^
-DAVIF_CODEC_AVM=OFF ^
-DAVIF_CODEC_DAV1D=SYSTEM ^
-DAVIF_CODEC_LIBGAV1=SYSTEM ^
-DAVIF_CODEC_RAV1E=OFF ^
-DAVIF_CODEC_SVT=OFF ^
-DAVIF_ENABLE_COMPLIANCE_WARDEN=OFF ^
-DAVIF_ENABLE_EXPERIMENTAL_GAIN_MAP=OFF ^
-DAVIF_ENABLE_EXPERIMENTAL_METAV1=OFF ^
-DAVIF_ENABLE_EXPERIMENTAL_SAMPLE_TRANSFORM=OFF ^
-DAVIF_ENABLE_EXPERIMENTAL_YCGCO_R=OFF ^
-DAVIF_ENABLE_NODISCARD=OFF ^
-DAVIF_ENABLE_WERROR=OFF ^
-DAVIF_GTEST=OFF ^
-DAVIF_JPEG=SYSTEM ^
-DAVIF_LIBYUV=SYSTEM ^
-DAVIF_LOCAL_FUZZTEST=OFF ^
-DAVIF_ZLIBPNG=SYSTEM ^
-DBUILD_SHARED_LIBS=ON ^
-DFETCHCONTENT_FULLY_DISCONNECTED=OFF ^
-DFETCHCONTENT_QUIET=OFF ^
-DFETCHCONTENT_UPDATES_DISCONNECTED=OFF ^
-DLIBYUV_INCLUDE_DIR=%PATH_INSTALL%\include\ ^
-DLIBYUV_LIBRARY=%PATH_INSTALL%\lib\libyuv.lib ^
%PATH_SRC%\%1

%PATH_BIN_CYGWIN%\bash %CYGPATH_MODULES_COMMON%/ninja.sh "%AVX%" "%CYGPATH_BUILD%/%1" "%NUMBER_OF_PROCESSORS%"
sed -i 's/DWIN32/DWIN32 \/DLIBYUV_USING_SHARED_LIBRARY=1/g' %CYGPATH_BUILD%/%1/build.ninja
%NINJA% install

	REM -DAVIF_BUILD_APPS=ON > avifenc.exe avifdec.exe
for %%X in (avif.dll) do (
	xcopy /C /F /Y %PATH_BUILD%\%1\%%~nX.pdb %PATH_INSTALL%\bin\*
	call do_php %PATH_UTILS%\sub\version.php %1 %PATH_INSTALL%\bin\%%X
)