@echo off && call %PATH_MODULES_COMMON%\init.bat %1 cmake nocxx

cmake %CMAKE_OPTS% -G %CMAKE_TGT_NINJA% ^
-DCMAKE_UNITY_BUILD=1 ^
-DCMAKE_INSTALL_PREFIX=%PATH_INSTALL% ^
-DLIBDEFLATE_BUILD_GZIP=OFF ^
-DLIBDEFLATE_BUILD_SHARED_LIB=ON ^
-DLIBDEFLATE_BUILD_STATIC_LIB=OFF ^
-DLIBDEFLATE_BUILD_TESTS=OFF ^
-DLIBDEFLATE_COMPRESSION_SUPPORT=ON ^
-DLIBDEFLATE_DECOMPRESSION_SUPPORT=ON ^
-DLIBDEFLATE_FREESTANDING=OFF ^
-DLIBDEFLATE_GZIP_SUPPORT=ON ^
-DLIBDEFLATE_USE_SHARED_LIB=ON ^
-DLIBDEFLATE_ZLIB_SUPPORT=ON ^
%PATH_SRC%\%1

%PATH_BIN_CYGWIN%\bash %CYGPATH_MODULES_COMMON%/ninja.sh "%AVX%" "%CYGPATH_BUILD%/%1" "%NUMBER_OF_PROCESSORS%"
%NINJA% install

xcopy /C /F /Y %PATH_BUILD%\%1\deflate.pdb %PATH_INSTALL%\bin\*
call do_php %PATH_UTILS%\sub\version.php %1 %PATH_INSTALL%\bin\deflate.dll