@echo off && call %PATH_MODULES_COMMON%\init.bat %1 cmake nocxx

cmake %CMAKE_OPTS% -G %CMAKE_TGT_NINJA% ^
-DBUILD_SHARED_LIBS=ON ^
-DCMAKE_INSTALL_PREFIX=%PATH_INSTALL% ^
-DCMAKE_BUILD_TYPE=%CMAKE_BUILD_TYPE% ^
-DEVENT__DISABLE_DEBUG_MODE=ON ^
-DEVENT__DISABLE_THREAD_SUPPORT=OFF ^
-DEVENT__DISABLE_OPENSSL=OFF ^
-DEVENT__DISABLE_BENCHMARK=ON ^
-DEVENT__DISABLE_TESTS=ON ^
-DEVENT__DISABLE_REGRESS=ON ^
-DEVENT__DISABLE_SAMPLES=ON ^
-DEVENT__COVERAGE=OFF ^
-DEVENT__ENABLE_VERBOSE_DEBUG=OFF ^
-DEVENT__DISABLE_MM_REPLACEMENT=OFF ^
-DEVENT__DISABLE_MBEDTLS=ON ^
-DEVENT__DISABLE_CLOCK_GETTIME=OFF ^
-DEVENT__FORCE_KQUEUE_CHECK=OFF ^
-DEVENT__MSVC_STATIC_RUNTIME=OFF ^
-DEVENT__DOXYGEN=OFF ^
-DOPENSSL_ROOT_DIR=%PATH_INSTALL_OSSL% ^
-DOPENSSL_INCLUDE_DIR=%PATH_INSTALL_OSSL%\include ^
-DGIT_EXECUTABLE=%PATH_BIN_GIT%\git.exe ^
%PATH_SRC%\%1

%PATH_BIN_CYGWIN%\bash %CYGPATH_MODULES_COMMON%/ninja.sh "%AVX%" "%CYGPATH_BUILD%/%1" "%NUMBER_OF_PROCESSORS%"
%NINJA% install

DEL /Q /F %PATH_INSTALL%\bin\event_rpcgen.py
for %%F in (event event_extra event_openssl event_core) do (
	call do_php %PATH_UTILS%\sub\version.php %1 %PATH_INSTALL%\lib\%%F.dll
	move /Y %PATH_INSTALL%\lib\%%F.dll %PATH_INSTALL%\bin
	xcopy /C /F /Y %PATH_BUILD%\%1\bin\%%F.pdb %PATH_INSTALL%\bin\*
)