@echo off && call %PATH_MODULES_COMMON%\init.bat %1 cmake

cmake %CMAKE_OPTS% -G %CMAKE_TGT_NINJA% ^
-DCMAKE_INSTALL_PREFIX=%PATH_INSTALL% ^
-DCMAKE_BUILD_TYPE=%CMAKE_BUILD_TYPE% ^
-DCMAKE_DISABLE_FIND_PACKAGE_Doxygen=1 ^
-DBUILD_SHARED_LIBS=ON ^
-DENABLE_PLUGIN_LOADING=ON ^
-DWITH_LIBDE265=OFF ^
-DWITH_X265=OFF ^
-DWITH_X265_PLUGIN=OFF ^
-DWITH_DAV1D=ON ^
-DWITH_DAV1D_PLUGIN=OFF ^
-DWITH_AOM_DECODER=ON ^
-DWITH_AOM_DECODER_PLUGIN=OFF ^
-DWITH_AOM_ENCODER=ON ^
-DWITH_AOM_ENCODER_PLUGIN=OFF ^
-DWITH_SvtEnc=OFF ^
-DWITH_SvtEnc_PLUGIN=OFF ^
-DWITH_RAV1E=OFF ^
-DWITH_RAV1E_PLUGIN=OFF ^
-DWITH_LIBSHARPYUV=ON ^
-DWITH_UNCOMPRESSED_CODEC=ON ^
-DWITH_GDK_PIXBUF=ON ^
-DWITH_REDUCED_VISIBILITY=OFF ^
-DWITH_EXAMPLES=ON ^
-DBUILD_TESTING=OFF ^
-DWITH_FUZZERS=OFF ^
-DWITH_DEFLATE_HEADER_COMPRESSION=ON ^
-DENABLE_MULTITHREADING_SUPPORT=ON ^
-DENABLE_PARALLEL_TILE_DECODING=ON ^
-DWITH_FFMPEG_DECODER=OFF ^
-DWITH_JPEG_DECODER=ON ^
-DWITH_JPEG_DECODER_PLUGIN=OFF ^
-DWITH_JPEG_ENCODER=ON ^
-DWITH_JPEG_ENCODER_PLUGIN=OFF ^
-DWITH_KVAZAAR=OFF ^
-DWITH_LIBDE265=OFF ^
-DWITH_LIBDE265_PLUGIN=OFF ^
-DWITH_OpenJPEG_DECODER=OFF ^
-DWITH_OpenJPEG_ENCODER=OFF ^
-DZLIB_LIBRARY=%PATH_INSTALL%\lib\zlib.lib ^
-DZLIB_INCLUDE_DIR=%PATH_INSTALL%\include ^
-DLIBSHARPYUV_INCLUDE_DIR=%PATH_INSTALL%\include\webp ^
-DLIBSHARPYUV_LIBRARY=%PATH_INSTALL%\lib\libsharpyuv.lib ^
%PATH_SRC%\%1

%PATH_BIN_CYGWIN%\bash %CYGPATH_MODULES_COMMON%/ninja.sh "%AVX%" "%CYGPATH_BUILD%/%1" "%NUMBER_OF_PROCESSORS%"
%NINJA% install

for %%X in (examples\heif-thumbnailer.pdb examples\heif-enc.pdb examples\heif-convert.pdb examples\heif-info.pdb libheif\heif.pdb) do (xcopy /C /F /Y %PATH_BUILD%\%1\%%X %PATH_INSTALL%\bin\*)
call do_php %PATH_UTILS%\sub\version.php %1 %PATH_INSTALL%\bin\heif.dll
for %%X in (heif-thumbnailer.exe heif-enc.exe heif-convert.exe heif-info.exe) do (call do_php %PATH_UTILS%\sub\version.php %1 %PATH_INSTALL%\bin\%%X)