@echo off && call %PATH_MODULES_COMMON%\init.bat %1 cmake

cmake %CMAKE_OPTS% -G %CMAKE_TGT_NINJA% ^
-DCMAKE_INSTALL_PREFIX=%PATH_INSTALL% ^
-DCMAKE_BUILD_TYPE=%CMAKE_BUILD_TYPE% ^
-DBUILD_SHARED_LIBS=ON ^
-DENABLE_PLUGIN_LOADING=ON ^
-DWITH_LIBDE265=OFF ^
-DWITH_X265=OFF ^
-DWITH_DAV1D=ON ^
-DWITH_AOM_ENCODER=ON ^
-DWITH_AOM_DECODER=ON ^
-DWITH_SvtEnc=OFF ^
-DWITH_RAV1E=OFF ^
-DWITH_EXAMPLES=OFF ^
-DWITH_DEFLATE_HEADER_COMPRESSION=ON ^
-DENABLE_MULTITHREADING_SUPPORT=ON ^
-DENABLE_PARALLEL_TILE_DECODING=ON ^
-DZLIB_LIBRARY=%PATH_INSTALL%\lib\zlib.lib ^
-DZLIB_INCLUDE_DIR=%PATH_INSTALL%\include ^
%PATH_SRC%\%1 

%PATH_BIN_CYGWIN%\bash %CYGPATH_MODULES_COMMON%/ninja.sh "%AVX%" "%CYGPATH_BUILD%/%1" "%NUMBER_OF_PROCESSORS%"
%NINJA% install

xcopy /C /F /Y %PATH_BUILD%\%1\libheif\heif.pdb %PATH_INSTALL%\bin\*
call do_php %PATH_UTILS%\sub\version.php %1 %PATH_INSTALL%\bin\heif.dll
