@echo off && call %PATH_MODULES_COMMON%\init.bat %1 cmake
REM goto shared
cmake %CMAKE_OPTS% -G %CMAKE_TGT_NINJA% ^
-DCMAKE_INSTALL_PREFIX=%PATH_INSTALL% ^
-DCMAKE_BUILD_TYPE=%CMAKE_BUILD_TYPE% ^
-DGIF_LIBRARY=%PATH_INSTALL%\lib\giflib.lib ^
-DBUILD_SHARED_LIBS=ON ^
-DWEBP_LINK_STATIC=OFF ^
-DWEBP_ENABLE_SIMD=ON ^
-DWEBP_BUILD_ANIM_UTILS=ON ^
-DWEBP_BUILD_CWEBP=OFF ^
-DWEBP_BUILD_DWEBP=OFF ^
-DWEBP_BUILD_GIF2WEBP=OFF ^
-DWEBP_BUILD_IMG2WEBP=OFF ^
-DWEBP_BUILD_VWEBP=OFF ^
-DWEBP_BUILD_WEBPINFO=OFF ^
-DWEBP_BUILD_LIBWEBPMUX=ON ^
-DWEBP_BUILD_WEBPMUX=OFF ^
-DWEBP_BUILD_EXTRAS=ON ^
-DWEBP_BUILD_WEBP_JS=OFF ^
-DWEBP_USE_THREAD=ON ^
-DWEBP_NEAR_LOSSLESS=ON ^
-DWEBP_ENABLE_SWAP_16BIT_CSP=ON ^
-DWEBP_UNICODE=OFF ^
-DWEBP_ENABLE_WUNUSED_RESULT=OFF ^
%PATH_SRC%\%1

%PATH_BIN_CYGWIN%\bash %CYGPATH_MODULES_COMMON%/ninja.sh "%AVX%" "%CYGPATH_BUILD%/%1" "%NUMBER_OF_PROCESSORS%"
sed -i -E 's/WEBP_EXTERN extern/WEBP_EXTERN __declspec^(dllexport^)/g' %CYGPATH_SRC%/%1/src/webp/types.h
%NINJA% install

for %%X in (libsharpyuv libwebpdecoder libwebp libwebpdemux libwebpmux) do (
	xcopy /C /F /Y %PATH_BUILD%\%1\%%X.pdb %PATH_INSTALL%\bin\*
	call do_php %PATH_UTILS%\sub\version.php %1 %PATH_INSTALL%\bin\%%X.dll
)