@echo off && call %PATH_MODULES_COMMON%\init.bat %1 cmake nocxx

if "%ARG_CMOPTS%"=="1" (@echo on)
cmake %CMAKE_OPTS% -G %CMAKE_TGT_NINJA% ^
-DCMAKE_INSTALL_PREFIX=%PATH_INSTALL% ^
-DENABLE_COMMONCRYPTO=OFF ^
-DENABLE_GNUTLS=OFF ^
-DENABLE_MBEDTLS=OFF ^
-DENABLE_OPENSSL=ON ^
-DENABLE_WINDOWS_CRYPTO=ON ^
-DENABLE_BZIP2=ON ^
-DENABLE_LZMA=ON ^
-DENABLE_ZSTD=ON ^
-DENABLE_FDOPEN=ON ^
-DBUILD_TOOLS=OFF ^
-DBUILD_REGRESS=OFF ^
-DBUILD_EXAMPLES=OFF ^
-DBUILD_DOC=OFF ^
-DBUILD_SHARED_LIBS=ON ^
-DLIBZIP_DO_INSTALL=ON ^
-DSHARED_LIB_VERSIONNING=ON ^
%PATH_SRC%\%1
@echo off
if "%ARG_CMOPTS%"=="1" (exit /B)

%PATH_BIN_CYGWIN%\bash %CYGPATH_MODULES_COMMON%/ninja.sh "%AVX%" "%CYGPATH_BUILD%/%1" "%NUMBER_OF_PROCESSORS%"
%NINJA% install

xcopy /C /F /Y %PATH_BUILD%\%1\lib\*.pdb %PATH_INSTALL%\bin\*

call do_php %PATH_UTILS%\sub\version.php %1 %PATH_INSTALL%\bin\zip.dll