@echo off && call %PATH_MODULES_COMMON%\init.bat %1 cmake nocxx

cmake %CMAKE_OPTS% -G %CMAKE_TGT_NINJA% ^
-DCMAKE_INSTALL_PREFIX=%PATH_INSTALL% ^
-DENABLE_LIB_ONLY=ON ^
-DENABLE_APP=OFF ^
-DENABLE_EXAMPLES=OFF ^
-DENABLE_DOC=OFF ^
-DENABLE_STATIC_CRT=OFF ^
-DENABLE_WERROR=OFF ^
-DENABLE_DEBUG=OFF ^
-DENABLE_THREADS=ON ^
-DENABLE_FAILMALLOC=OFF ^
-DWITH_LIBXML2=ON ^
-DWITH_JEMALLOC=ON ^
-DENABLE_HPACK_TOOLS=OFF ^
-DWITH_MRUBY=OFF ^
-DWITH_LIBBPF=OFF ^
-DWITH_NEVERBLEED=OFF ^
-DBUILD_STATIC_LIBS=NO ^
-DBUILD_SHARED_LIBS=YES ^
-DCMAKE_DISABLE_FIND_PACKAGE_Systemd=1 ^
-DWITH_WOLFSSL=OFF ^
-DENABLE_HTTP3=ON ^
%PATH_SRC%\%1

%PATH_BIN_CYGWIN%\bash %CYGPATH_MODULES_COMMON%/ninja.sh "%AVX%" "%CYGPATH_BUILD%/%1" "%NUMBER_OF_PROCESSORS%"
%NINJA% install

xcopy /C /F /Y %PATH_BUILD%\%1\lib\nghttp2.pdb %PATH_INSTALL%\bin\*
call do_php %PATH_UTILS%\sub\version.php %1 %PATH_INSTALL%\bin\nghttp2.dll