cd ..
rmdir /S /Q %PATH_BUILD%\pcre
mkdir %PATH_BUILD%\pcre
cd /D %PATH_BUILD%\pcre
cmake -Wno-dev -G "NMake Makefiles" -DCMAKE_INSTALL_PREFIX=%PATH_INSTALL% -DCMAKE_BUILD_TYPE=%CMAKE_BUILD_TYPE% -DBUILD_SHARED_LIBS=ON -DPCRE_BUILD_TESTS=OFF -DPCRE_BUILD_PCRECPP=OFF -DPCRE_BUILD_PCREGREP=OFF -DPCRE_SUPPORT_PCREGREP_JIT=OFF -DPCRE_SUPPORT_UTF=ON -DPCRE_SUPPORT_UNICODE_PROPERTIES=ON -DPCRE_NEWLINE=CRLF -DINSTALL_MSVC_PDB=ON -DBZIP2_INCLUDE_DIR=%PATH_INSTALL%\inculde %PATH_SRC%\pcre
%PATH_BIN_CYGWIN%\bash %CYGPATH_MODULES%/pcre.sh "%AVXSED%"
nmake %NMAKE_OPTS% clean install
cd /D %PATH_MODULES%