call %PATH_MODULES_COMMON%\init.bat %1 cmake

cmake %CMAKE_OPTS% ^
-DCMAKE_INSTALL_PREFIX=%PATH_INSTALL% ^
-DCMAKE_BUILD_TYPE=%CMAKE_BUILD_TYPE% ^
-DBUILD_SHARED_LIBS=ON ^
-DPCRE_BUILD_TESTS=OFF ^
-DPCRE_BUILD_PCRECPP=OFF ^
-DPCRE_BUILD_PCREGREP=OFF ^
-DPCRE_SUPPORT_PCREGREP_JIT=OFF ^
-DPCRE_SUPPORT_UTF=ON ^
-DPCRE_SUPPORT_UNICODE_PROPERTIES=ON ^
-DPCRE_NEWLINE=CRLF ^
-DINSTALL_MSVC_PDB=ON ^
-DBZIP2_INCLUDE_DIR=%PATH_INSTALL%\inculde ^
-DPCRE_BUILD_PCRE16=ON ^
-DPCRE_BUILD_PCRE32=ON ^
-DPCRE_SUPPORT_LIBZ=ON ^
-DPCRE_SUPPORT_LIBEDIT=OFF ^
-DPCRE_SUPPORT_LIBREADLINE=OFF ^
%PATH_SRC%\%1

%PATH_BIN_CYGWIN%\bash %CYGPATH_MODULES_COMMON%/flags.sh "%AVXSED%" "%CYGPATH_BUILD%/%1" "%NUMBER_OF_PROCESSORS%"
nmake %NMAKE_OPTS% clean install

for %%X in (pcre16 pcre32) do (xcopy /C /F /Y %PATH_BUILD%\%1\%%X.pdb %PATH_INSTALL%\bin\*)
for %%X in (pcre pcre16 pcre32 pcreposix) do (call do_php %PATH_UTILS%\sub\version.php %1 %PATH_INSTALL%\bin\%%X.dll)