call %PATH_BATCH%\go.bat wineditline NOLOG
call %PATH_BATCH%\go.bat liblzma NOLOG
call %PATH_BATCH%\go.bat libzip NOLOG
call %PATH_BATCH%\go.bat libxpm NOLOG
call %PATH_BATCH%\go.bat libpng NOLOG
call %PATH_BATCH%\go.bat jpeg NOLOG
call %PATH_BATCH%\go.bat tidy NOLOG
call %PATH_BATCH%\go.bat libxdiff NOLOG
call %PATH_BATCH%\go.bat freetype2 NOLOG
call %PATH_BATCH%\go.bat libffi NOLOG
call %PATH_BATCH%\go.bat geos NOLOG
call %PATH_BATCH%\go.bat php NOLOG