@echo off && call %PATH_MODULES_COMMON%\init.bat %1 cmake

if exist %PATH_INSTALL%\_%1\. rmdir /S /Q %PATH_INSTALL%\_%1
mkdir %PATH_INSTALL%\_%1

REM https://proj.org/install.html#cmake-configure-options
REM -DPROJ_OUTPUT_NAME=libproj ^
if "%ARG_CMOPTS%"=="1" (@echo on)
cmake %CMAKE_OPTS% -G %CMAKE_TGT_NINJA% ^
-DCMAKE_UNITY_BUILD=1 ^
-DCMAKE_INSTALL_PREFIX=%PATH_INSTALL%\_%1 ^
-DCMAKE_INSTALL_MANDIR=%PATH_INSTALL%\_%1 ^
-DBUILD_APPS=ON ^
-DBUILD_CCT=ON ^
-DBUILD_CS2CS=ON ^
-DBUILD_GEOD=ON ^
-DBUILD_GIE=ON ^
-DBUILD_PROJ=ON ^
-DBUILD_PROJINFO=ON ^
-DBUILD_PROJSYNC=ON ^
-DBUILD_SHARED_LIBS=ON ^
-DENABLE_CURL=ON ^
-DENABLE_TIFF=ON ^
-DBUILD_TESTING=OFF ^
-DENABLE_IPO=ON ^
-DPROJ_DATA_ENV_VAR_TRIED_LAST=OFF ^
-DINSTALL_LEGACY_CMAKE_FILES=OFF ^
-DUSE_CCACHE=OFF ^
-DUSE_PKGCONFIG_REQUIRES=OFF ^
-DBUILD_EXAMPLES=OFF ^
-DEMBED_RESOURCE_FILES=ON ^
-DUSE_ONLY_EMBEDDED_RESOURCE_FILES=OFF ^
-DPROJ_OBJECT_LIBRARIES_POSITION_INDEPENDENT_CODE=ON ^
-DEMBED_PROJ_DATA_PATH=ON ^
-DEXPORT_PDB=OFF ^
%PATH_SRC%\%1
@echo off
if "%ARG_CMOPTS%"=="1" (exit /B)

%PATH_BIN_CYGWIN%\bash %CYGPATH_MODULES_COMMON%/ninja.sh "%AVX%" "%CYGPATH_BUILD%/%1" "%NUMBER_OF_PROCESSORS%"
%NINJA% install

for /f "tokens=*" %%G in ('dir %PATH_INSTALL%\_%1\bin\*.* /b') do (call do_php %PATH_UTILS%\sub\version.php %1 %PATH_INSTALL%\_%1\bin\%%G)
for /f "tokens=*" %%G in ('dir %PATH_BUILD%\%1\bin\*.pdb /b') do  (xcopy /C /F /Y %PATH_BUILD%\%1\bin\%%G %PATH_INSTALL%\_%1\bin\*)
xcopy /C /F /Y %PATH_BUILD%\%1\lib\*.lib %PATH_INSTALL%\_%1\lib\*