@echo off && call %PATH_UTILS%\init.bat %1 cmake nocxx

if "%ARG_CMOPTS%"=="1" (@echo on)
cmake %CMAKE_OPTS% -G %CMAKE_TGT_NINJA% ^
-DCMAKE_INSTALL_PREFIX=%PATH_INSTALL% ^
-DDEBUG=OFF ^
-DSKIP_SHARED=OFF ^
-DSKIP_STATIC=ON ^
-DDISABLE_LOGGING=OFF ^
-DSKIP_TESTS=ON ^
-DENABLE_SLOW_TESTS=OFF ^
-DAPR_STATIC=OFF ^
-DEXPAT=%PATH_INSTALL%\ ^
-DRELATIVE_RPATH=OFF ^
-DDOT_CLANGD=OFF ^
-DUSE_HOMEBREW=OFF ^
-DUSE_MACPORTS=OFF ^
-DUSE_UNBOUND=OFF ^
-DUSE_BROTLI=OFF ^
-DUSE_GSSAPI=OFF ^
%PATH_SRC%\%1
@echo off
if "%ARG_CMOPTS%"=="1" (exit /B)

%PATH_BIN_CYGWIN%\bash %CYGPATH_UTILS%/ninja.sh "%AVX%" "%CYGPATH_BUILD%/%1" "%NUMBER_OF_PROCESSORS%"
%NINJA% install

call do_php %PATH_UTILS%\sub\version.php %1 %PATH_INSTALL%\bin\libserf-2.dll