@echo off && call %PATH_MODULES_COMMON%\init.bat %1 cmake nocxx

if "%2"=="svn" (
	set CMAKE_SERF=^
	-DUSE_BROTLI=OFF
) else (
	set CMAKE_SERF=^
	-DUSE_BROTLI=ON
)
REM https://github.com/apache/serf/commit/9cf0878aafefa04df775d3e424f16ee07d423901
	REM -DUSE_UNBOUND=OFF ^
	REM -DUSE_GSSAPI=OFF ^
	REM %CMAKE_SERF% ^
cmake %CMAKE_OPTS% -G %CMAKE_TGT_NINJA% ^
-DCMAKE_POLICY_VERSION_MINIMUM=3.5 ^
-DSERF_WIN64=ON ^
-DCMAKE_INSTALL_PREFIX=%PATH_INSTALL% ^
-DDEBUG=OFF ^
-DSKIP_SHARED=OFF ^
-DSKIP_STATIC=ON ^
-DDISABLE_LOGGING=OFF ^
-DSKIP_TESTS=ON ^
-DENABLE_SLOW_TESTS=OFF ^
-DAPR_STATIC=OFF ^
-DAPR_ROOT=%PATH_INSTALL%\ ^
-DAPRUtil_ROOT=%PATH_INSTALL%\ ^
-DOPENSSL_ROOT_DIR=%PATH_INSTALL%\ ^
-DCMAKE_INSTALL_OLDINCLUDEDIR=%PATH_INSTALL%\include ^
-DEXPAT=%PATH_INSTALL%\ ^
-DRELATIVE_RPATH=OFF ^
-DDOT_CLANGD=OFF ^
-DUSE_HOMEBREW=OFF ^
-DUSE_MACPORTS=OFF ^
%PATH_SRC%\%1

%PATH_BIN_CYGWIN%\bash %CYGPATH_MODULES_COMMON%/ninja.sh "%AVX%" "%CYGPATH_BUILD%/%1" "%NUMBER_OF_PROCESSORS%"
%NINJA% install

call do_php %PATH_UTILS%\sub\version.php %1 %PATH_INSTALL%\bin\libserf-2.dll