cd ..
rmdir /S /Q %PATH_BUILD%\libevent
mkdir %PATH_BUILD%\libevent
cd /D %PATH_BUILD%\libevent
cmake -Wno-dev -G "NMake Makefiles" -DCMAKE_INSTALL_PREFIX=%PATH_INSTALL% -DCMAKE_BUILD_TYPE=%CMAKE_BUILD_TYPE% -DBUILD_SHARED_LIBS=ON -DGIT_EXECUTABLE=c:\PROGRA~1\Git\bin\git.exe -DEVENT__DISABLE_DEBUG_MODE=ON -DEVENT__DISABLE_THREAD_SUPPORT=OFF -DEVENT__DISABLE_OPENSSL=OFF -DEVENT__DISABLE_BENCHMARK=ON -DEVENT__DISABLE_TESTS=ON -DEVENT__DISABLE_REGRESS=ON -DEVENT__DISABLE_SAMPLES=ON -DEVENT__COVERAGE=OFF %PATH_SRC%\libevent
%PATH_BIN_CYGWIN%\bash %CYGPATH_MODULE_BAT%/libevent.sh "%AVXSED%"
nmake %NMAKE_OPTS% clean install
cd /D %PATH_MODULE_BAT%