git clone https://github.com/apache/apr.git
git clone https://github.com/apache/apr-iconv
git clone https://github.com/apache/apr-util.git
git clone https://github.com/google/brotli.git
git clone git://sourceware.org/git/bzip2.git
git clone https://github.com/c-ares/c-ares.git
git clone https://github.com/curl/curl.git
git clone https://github.com/winlibs/freetype.git
git clone https://github.com/apache/httpd.git
git clone https://github.com/akheron/jansson.git
git clone https://github.com/jemalloc/jemalloc.git
git clone https://github.com/disenone/libev-win
git clone https://github.com/libevent/libevent.git
git clone https://github.com/libexpat/libexpat.git
git clone https://github.com/winlibs/libiconv.git
git clone https://github.com/winlibs/libjpeg.git
git clone https://github.com/maxmind/libmaxminddb.git
git clone https://github.com/winlibs/libpng.git
git clone https://github.com/libssh2/libssh2.git
git clone https://github.com/opencor/libxdiff
git clone https://github.com/GNOME/libxml2.git
git clone https://github.com/winlibs/libxpm
git clone https://github.com/LuaDist/lua
git clone https://github.com/memcached/memcached
git clone https://github.com/pagespeed/mod_fcgid
git clone https://github.com/icing/mod_h2.git
git clone https://github.com/traceypooh/mod_h264_streaming--intra-keyframes.git
git clone https://github.com/maxmind/mod_maxminddb.git
git clone https://github.com/icing/mod_md
git clone https://github.com/nono303/mod_whatkilledus
git clone https://github.com/nghttp2/nghttp2.git
git clone https://git.nssm.cc/nssm/nssm.git
git clone https://github.com/openssl/openssl.git
git clone https://github.com/jwilk-mirrors/pcre
git clone https://github.com/websupport-sk/pecl-memcache.git
git clone https://github.com/php/pecl-text-xdiff
git clone https://github.com/deemru/php-cgi-spawner.git
git clone https://github.com/kjdev/php-ext-brotli.git
git clone https://github.com/php/php-src.git
git clone https://github.com/microsoft/php-sdk-binary-tools.git
